gt9x_2.4: Remove unused variables
drivers/input/touchscreen/gt9x_2.4/gt9xx.c: In function 'gtp_i2c_read':
drivers/input/touchscreen/gt9x_2.4/gt9xx.c:115:25: error: unused variable 'ts' [-Werror=unused-variable]
  struct goodix_ts_data *ts = i2c_get_clientdata(client);
                         ^~
drivers/input/touchscreen/gt9x_2.4/gt9xx.c: In function 'gtp_i2c_write':
drivers/input/touchscreen/gt9x_2.4/gt9xx.c:160:5: error: unused variable 'retries' [-Werror=unused-variable]
  u8 retries;
     ^~~~~~~
drivers/input/touchscreen/gt9x_2.4/gt9xx.c:158:25: error: unused variable 'ts' [-Werror=unused-variable]
  struct goodix_ts_data *ts = i2c_get_clientdata(client);
                         ^~
drivers/input/touchscreen/gt9x_2.4/gt9xx.c: In function 'goodix_ts_suspend':
drivers/input/touchscreen/gt9x_2.4/gt9xx.c:1911:16: error: unused variable 'i' [-Werror=unused-variable]
  int ret = -1, i;

Signed-off-by: Davide Garberi <dade.garberi@gmail.com>